Pierres/Models/Treat.cs
using System.Collections.Generic;

namespace Pierres.Models
{
  public class Treat
  {
    public Treat()
    {
      this.JoinEntities = new HashSet<FlavorTreat>();
    }

    public int TreatId { get; set; }
    public string Name { get; set; }
    public int Quantity { get; set; }
    public string Search { get; set; }
    public virtual ApplicationUser User { get; set; }
    public virtual ICollection<FlavorTreat> JoinEntities { get; }
  }
}

Pierres/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc;
using Pierres.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Pierres.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly PierresContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public FlavorsController(UserManager<ApplicationUser> userManager, PierresContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userFlavors = _db.Flavors.Where(entry => entry.User.Id == currentUser.Id).ToList();
      return View(userFlavors);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Flavor flavor)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flavor.User = currentUser;
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      var thisFlavor = _db.Flavors
        .Include(flavor => flavor.JoinEntities)
        .ThenInclude(join => join.Treat)
        .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public async Task<ActionResult> AddTreat(int id)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats.Where(entry => entry.User.Id == currentUser.Id), "TreatId", "Name");
      return View(thisFlavor);
    }

    [HttpPost]
    public async Task<ActionResult> AddTreat(Flavor flavor, int TreatId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flavor.User = currentUser;
      if (TreatId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteTreat(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(joinEntry => joinEntry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Pierres/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc;
using Pierres.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Pierres.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {

    private readonly PierresContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public TreatsController(UserManager<ApplicationUser> userManager, PierresContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userTreats = _db.Treats.Where(entry => entry.User.Id == currentUser.Id).ToList();
      return View(userTreats);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Treat treat, int FlavorId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      treat.User = currentUser;
      _db.Treats.Add(treat);
      _db.SaveChanges();
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      var thisTreat = _db.Treats
        .Include(treat => treat.JoinEntities)
        .ThenInclude(join => join.Flavor)
        .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    public ActionResult Edit(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat, int FlavorId)
    {
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public async Task<ActionResult> AddFlavor(int id)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors.Where(entry => entry.User.Id == currentUser.Id), "FlavorId", "Name");
      return View(thisTreat);
    }

    [HttpPost]
    public async Task<ActionResult> AddFlavor(Treat treat, int FlavorId)
    {
       var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      treat.User = currentUser;
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(joinEntry => joinEntry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Pierres/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@model Pierres.Models.Treat

<div class="jumbotron">
  <h1>Assign Treat to Flavor here!</h1>
</div>
<hr />
<div class="card addCard">
<h3>Assign @Html.DisplayFor(model => model.Name) to a Flavor:</h3>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)
  @Html.Label("Choose Flavor:")
  @Html.DropDownList("FlavorId")
  <button class="btn-warning" type="submit">Add to Flavor!</button>
}
</div>
<hr />

Pierres/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model Pierres.Models.Treat

<div class="jumbotron">
  <h1>Add a new Treat here!</h1>
</div>
<hr />
<div class="card createCard">
  @using (Html.BeginForm())
  {
    @Html.Label("Treat Name:")
    @Html.TextBoxFor(model => model.Name, new { required = "required" })
    <br>
    @Html.Label("Treat Quantity:")
    @Html.TextBoxFor(model => model.Quantity, new { type = "number", required = "required" })
    <br>
    <button class="btn-warning" type="submit">Add Treat!</button>
  }
</div>
<hr />

Pierres/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Pierres.Models.Treat

<div class="jumbotron">
  <h1>Delete @Html.DisplayFor(model => model.Name)?</h1>
</div>
<hr />
<div class="row rows">
@using (Html.BeginForm())
{
  <button class="btn-success" type="submit">Yes</button>
}
<button class="btn-danger">@Html.ActionLink("No", "Index")</button>
</div>
<hr />

Pierres/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@model Pierres.Models.Treat

<div class="jumbotron">
  <h1>Details for @Html.DisplayFor(model => model.Name):</h1>
</div>
<hr />
@if (User.Identity.IsAuthenticated)
{
  <div class="row">
    <div class="card tName">
      <h3>Treat Name:</h3>
      <p>@Html.DisplayFor(model => model.Name)</p>
    </div>
    <div class="card tQuantity">
      <h3>Treat Quantity:</h3>
      <p>@Html.DisplayFor(model => model.Quantity)</p>
    </div>
  </div>
  <hr />
  <div class="card treatFlav">
    @if (@Model.JoinEntities.Count == 0)
    {
      <h4>@Html.DisplayFor(model => model.Name) is not assigned under a Flavor!</h4>
    }
    else
    {
      <h4>@Html.DisplayFor(model => model.Name) is assigned to the following @Html.DisplayFor(model =>
    model.JoinEntities.Count) flavors:</h4>
      <ul>
        @foreach (var join in Model.JoinEntities)
        {
          <li>@Html.ActionLink(@join.Flavor.Name, "Details", "Flavors", new { id = join.Flavor.FlavorId })</li>
        }
      </ul>
    }
  </div>
  <hr />
  <div class="card flavRemove">
    @if (@Model.JoinEntities.Count == 0)
    {
      <h4>No Flavors to remove @Html.DisplayFor(model => model.Name) from.</h4>
    }
    else
    {
      <h4>Remove @Html.DisplayFor(model => model.Name) from Flavor:</h4>
      <ul>
        <div class="row">
          @foreach (var join in Model.JoinEntities)
          {
            @using (Html.BeginForm("DeleteFlavor", "Treats"))
            {
              @Html.Hidden("joinId", @join.FlavorTreatId)
              <button class="btn-danger" type="submit">@join.Flavor.Name</button>
            }
          }
        </div>
      </ul>
    }
  </div>
  <hr />
  <button class="btn-warning">@Html.ActionLink("Edit Treat", "Edit", new { id = Model.TreatId })</button>
  <button class="btn-warning">@Html.ActionLink("Delete Treat", "Delete", new { id = Model.TreatId })</button>
  <button class="btn-warning">@Html.ActionLink("Add Treat to Flavor", "AddFlavor", new { id = Model.TreatId })</button>
  <hr />
}
else
{
  <div class="row">
    <div class="card tName">
      <h3>Treat Name:</h3>
      <p>@Html.DisplayFor(model => model.Name)</p>
    </div>
    <div class="card tQuantity">
      <h3>Treat Quantity:</h3>
      <p>@Html.DisplayFor(model => model.Quantity)</p>
    </div>
  </div>
  <hr />
  <div class="card treatFlav">
    @if (@Model.JoinEntities.Count == 0)
    {
      <h4>@Html.DisplayFor(model => model.Name) is not assigned under a Flavor!</h4>
    }
    else
    {
      <h4>@Html.DisplayFor(model => model.Name) is assigned to the following @Html.DisplayFor(model =>
    model.JoinEntities.Count) flavors:</h4>
      <ul>
        @foreach (var join in Model.JoinEntities)
        {
          <li>@Html.ActionLink(@join.Flavor.Name, "Details", "Flavors", new { id = join.Flavor.FlavorId })</li>
        }
      </ul>
    }
  </div>
  <hr />
}

Pierres/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@using Pierres.Models
@model Pierres.Models.Treat

<div class="jumbotron">
  <h1>Edit @Html.DisplayFor(model => model.Name)</h1>
</div>
<hr />
<div class="card createCard">
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.TreatId)
    @Html.Label("Edit Treat Name:")
    @Html.EditorFor(model => model.Name, new { required = "required" })
    <br>
    @Html.Label("Edit Treat Quantity:")
    @Html.EditorFor(model => model.Quantity, new { type = "number", required = "required" })
    <br>
    <button class="btn-warning" type="submit">Update Treat!</button>
  }
</div>
<hr />

Pierres/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

@using Pierres.Models
@model IEnumerable<Pierres.Models.Treat>;

<div class="jumbotron">
  <h1>Avaliable Treats For @User.Identity.Name</h1>
</div>
<hr />
<div class="card treatIndex">
  @if (Model.Any())
  {
    <ul>
      <h4>Avaliable Treats!</h4>
      <p>Name - Quantity</p>
      @foreach (Treat treat in Model)
      {
        <li>@Html.ActionLink($"{treat.Name}", "Details", new { id = treat.TreatId }) - @Html.DisplayFor(model =>
      treat.Quantity)</li>
      }
    </ul>
  }
  else
  {
    <h3>No Treats have been made yet! Get Pierre to teach you the ways!</h3>
  }
</div>
<hr />
<button class="btn-warning">@Html.ActionLink("Add new Treat!", "Create")</button>
<hr />